 config/security.yaml
# Security Configuration

authentication:
  jwt:
    algorithm: "HS256"
    access_token_expires: 3600  # 1 hour
    refresh_token_expires: 2592000  # 30 days
    
  password:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: false
    
authorization:
  roles:
    - name: "admin"
      permissions:
        - "all"
    - name: "user"
      permissions:
        - "predict"
        - "view_own_data"
    - name: "analyst"
      permissions:
        - "predict"
        - "view_all_data"
        - "export_data"

rate_limiting:
  default: "200 per day, 50 per hour"
  api_predict: "10 per minute"
  api_batch: "1 per minute"
  auth_login: "5 per minute"
  
input_validation:
  email_text:
    min_length: 10
    max_length: 10000
    
  username:
    min_length: 3
    max_length: 20
    pattern: "^[a-zA-Z0-9_]+$"
    
  password:
    min_length: 8
    max_length: 128
    
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    
headers:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
  Content-Security-Policy: "default-src 'self'"
